# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: Run the tests
        run: mvn -ntp -B test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn -ntp -B -Dmaven.test.skip=true -B package
      - uses: actions/upload-artifact@v4
        with:
          name: lottie4j
          path: core/target/*.jar
      - uses: actions/upload-artifact@v4
        with:
          name: lottie4j
          path: fxplayer/target/*.jar